# Generated by Django 5.0.6 on 2026-04-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couple",
            name="bride_father_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="bride_full_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="bride_mother_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="groom_father_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="groom_full_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="groom_linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="couple",
            name="groom_mother_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couple",
            name="opening_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="couple",
            name="opening_quote_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="couple",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="api.couple",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="location_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="maps_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="time_end",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="time_start",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="couple",
            name="bride_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="couple",
            name="groom_name",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "attendance",
                    models.CharField(
                        choices=[("hadir", "Hadir"), ("tidak_hadir", "Tidak Hadir")],
                        max_length=20,
                    ),
                ),
                ("guests", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="api.couple",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="api.couple",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="api.couple",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
