services:
  undangan-nikah-ghulam-db:
    image: postgres:16
    container_name: undangan-nikah-ghulam-db
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - undangan-nikah-ghulam-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  undangan-nikah-ghulam-network:
    name: undangan-nikah-ghulam-network
    driver: bridge